#!/usr/bin/env python3
"""Build the site.

  src/shared/            reusable pieces (styles, fonts, MathJax, menu, theme, contents rail), copied to docs/shared/
  src/posts/<slug>/      one folder per post:
      page.html          the page, with <!--FX:name--> placeholders for data figures
      post.css, *.js     post-specific styles and scripts (copied as is)
      figs/<name>.*      data figures: html fragment + css + js, bundled into figures.css / figures.js
      data.js            figure data (window.FIGDATA), regenerated by data-src/extract.py
  src/index.html         site home

Outputs
  ../public/blog/        inside the Astro site: shared/ and <slug>/ are served as-is at /blog/<slug>/
                         (the blog index itself is the Astro page src/pages/blog/index.astro)
  dist/<slug>.html       one self-contained file per post (fonts, MathJax, data inlined), for sharing offline

usage: python3 build.py [slug ...]      (default: every post)
"""
import os, re, sys, shutil, base64
ROOT = os.path.dirname(os.path.abspath(__file__))
SRC, DIST = os.path.join(ROOT, 'src'), os.path.join(ROOT, 'dist')
DOCS = os.path.normpath(os.path.join(ROOT, '..', 'public', 'blog'))   # served by the Astro site
TAG = re.compile(r'_[A-Z]{3}\d+B(?:_swa_v2)?')   # internal training-data tag on run ids: must never ship
TEXT = ('.html', '.css', '.js', '.json', '.md', '.txt', '.svg')

def rd(p): return open(p, encoding='utf-8').read()
def wr(p, s):
    os.makedirs(os.path.dirname(p), exist_ok=True)
    open(p, 'w', encoding='utf-8').write(s)

def build_post(slug):
    P, O = os.path.join(SRC, 'posts', slug), os.path.join(DOCS, slug)
    page = rd(os.path.join(P, 'page.html'))
    css, js = [], []
    for n in re.findall(r'<!--FX:([a-z0-9_-]+)-->', page):
        f = os.path.join(P, 'figs', n)
        page = page.replace(f'<!--FX:{n}-->', rd(f + '.html').strip())
        css.append(f'/* ---- {n} ---- */\n' + rd(f + '.css'))
        js.append(f'/* ---- {n} ---- */\n' + rd(f + '.js'))
    if os.path.isdir(O): shutil.rmtree(O)
    os.makedirs(O)
    wr(os.path.join(O, 'index.html'), page)
    wr(os.path.join(O, 'figures.css'), '/* data figures, bundled from figs/*.css by build.py */\n' + '\n'.join(css))
    wr(os.path.join(O, 'figures.js'), '/* data figures, bundled from figs/*.js by build.py */\n' + '\n'.join(js))
    for f in os.listdir(P):   # post.css, illustrations.js, data.js, images ...
        if f in ('page.html', 'figs', 'data-src') or f.startswith('.'): continue
        s = os.path.join(P, f)
        (shutil.copytree if os.path.isdir(s) else shutil.copy)(s, os.path.join(O, f))
    return O

def standalone(slug):
    """Inline every local stylesheet, script, and font of docs/<slug>/index.html into dist/<slug>.html."""
    O = os.path.join(DOCS, slug)
    page = rd(os.path.join(O, 'index.html'))
    def css_inline(m):
        p = os.path.normpath(os.path.join(O, m.group(1))); d = os.path.dirname(p)
        s = re.sub(r'url\((?!data:)([^)]+\.woff2)\)', lambda u: 'url(data:font/woff2;base64,' +
                   base64.b64encode(open(os.path.join(d, u.group(1)), 'rb').read()).decode() + ')', rd(p))
        return f'<style>\n{s}</style>'
    page = re.sub(r'<link rel="stylesheet" href="([^":]+)">', css_inline, page)
    mj = re.search(r'<script defer src="([^":]+tex-svg\.min\.js)"></script>\n', page)
    page = page.replace(mj.group(0), '')
    js = lambda p: rd(os.path.normpath(os.path.join(O, p))).replace('</script', '<\\/script')
    page = re.sub(r'<script src="([^":]+)"></script>', lambda m: f'<script>\n{js(m.group(1))}</script>', page)
    # MathJax last, with the TeX extensions it would otherwise fetch, marked as preloaded
    mjdir = os.path.dirname(mj.group(1)); extra = ''
    extdir = os.path.normpath(os.path.join(O, mjdir, 'input/tex/extensions'))
    for f in sorted(os.listdir(extdir)) if os.path.isdir(extdir) else []:
        extra += f'<script>\n{js(os.path.join(mjdir, "input/tex/extensions", f))}\nMathJax.loader.preLoad("[tex]/{f[:-3]}");\n</script>\n'
    page = page.replace('</body>', f'<script>\n{js(mj.group(1))}</script>\n{extra}</body>')
    left = re.findall(r'<(?:script|link|img)[^>]*(?:src|href)="(?!https?:|#|data:)[^"]+"', page)
    assert not left, left
    wr(os.path.join(DIST, slug + '.html'), page)
    return len(page.encode())

def main():
    posts = sys.argv[1:] or sorted(d for d in os.listdir(os.path.join(SRC, 'posts')) if not d.startswith('.'))
    if os.path.isdir(os.path.join(DOCS, 'shared')): shutil.rmtree(os.path.join(DOCS, 'shared'))
    shutil.copytree(os.path.join(SRC, 'shared'), os.path.join(DOCS, 'shared'), ignore=shutil.ignore_patterns('*.md'))
    # (no index.html here: /blog/ is the Astro page; list the post in src/content/blog/ instead)
    for slug in posts:
        build_post(slug)
        n = standalone(slug)
        print(f'{slug}: public/blog/{slug}/  +  dist/{slug}.html ({n / 1e6:.1f} MB)')
    # safety net: nothing published may carry the internal tag
    for base in (DOCS, DIST):
        for dp, _, fs in os.walk(base):
            for f in fs:
                if f.endswith(TEXT):
                    assert not TAG.search(rd(os.path.join(dp, f))), os.path.join(dp, f)

if __name__ == '__main__':
    main()
